### ISSUE TITLE
expenseApp.d.ts seems to be missing

### ISSUE THREAD

**Issue by jseminck** [DanWahlin/AngularTypeScript#1]
Hi Dan,

I followed your talk at ng-conf and now watching your course on TypeScript on PS. I want to give TS a try in combination with Angular and want to use this project and the "AngularIn20TypeScript" as examples to learn from.

I was just browsing the repo on Github and noticed in the app,module.ts file that you have a reference to an expenseApp.d.ts file which is supposed to be located under /tools/typing/. However I cannot find this folder - I assume that it is generated by running tsd which will grab all the dependencies from the tsd.json file and bundle them in tsd.d.ts - but we still need the expenseApp.d.ts from somewhere right?

https://github.com/DanWahlin/AngularTypeScript/blob/master/src/app/expenseApp/app.module.ts
reference path="../../../tools/typings/expenseApp.d.ts"

I'm guessing you may have forgotton to commit this by ignoring the whole tools/typing folder in your git commits. Or is it not necessary? (if so please close the issue)

Thanks

**Comment by DanWahlin** [comment]
The contents of that file are generated once you run "gulp" at the command-line. 

We'll update the readme with some details on running the tools. I'm on vacation right now though so it'll be at least 10 days before I get a chance. This particular app is here just to show the code for now since it relies on a lot of cloud services that would have to be setup.

But, in a nutshell run the following from the root of the project:

npm install gulp -g
npm install
tsd reinstall
gulp

You normally add an empty expenseApp.d.ts file in tools/typings with the following in it:

//{

//}

Every time you save a .ts file the gulp task will update the references in the file.
